version: 2
jobs:
  build:
    docker:
      - image: gigantum/circleci-common:a587c30a-2018-05-22
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Set Git credentials config
          command: git config --global user.email "noreply@gigantum.io" && git config --global user.name "CircleCI" && git config --global credential.helper store

      - run:
          name: Run mypy type checker
          command: |
            python3 -m mypy . --ignore-missing-imports --strict-optional

      - run:
          name: Set authentication credentials
          command: bash /home/circleci/project/.circleci/write_auth.sh

      - run:
          name: Run unit and coverage tests
          command: |
            redis-server &
            rqscheduler --interval=2 2> /dev/null &
            pytest --cov=lmcommon .
            coveralls

