version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    python:
      version: 3.6.1
    steps:
      - checkout
      - run: 
        name: Install build essentials
        command:
          - sudo apt-get update
          - sudo apt-get install build-essential libsnappy-dev
      - run: mkdir ~/leveldb; cd ~/leveldb; git clone https://github.com/google/leveldb.git; cd leveldb/; make;
      - run: sudo scp ~/leveldb/leveldb/out-static/lib* ~/leveldb/leveldb/out-shared/lib* /usr/local/lib/
      - run: cd ~/leveldb/leveldb/include/; sudo scp -r leveldb /usr/local/include/; sudo ldconfig
      - run: git config --global user.email "noreply@gigantum.io" && git config --global user.name "CircleCI"
      - run: sudo pip install -r requirements.txt
      - run: sudo pip install coveralls pytest-cov
      - run: pytest --cov=lmcommon .
      - run: coveralls

