version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    python:
      version: 3.6.1
    steps:
      - checkout
      - run: 
          name: Install build essentials
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential redis-server

      - run:
          name: Set Git credentials config
          command: git config --global user.email "noreply@gigantum.io" && git config --global user.name "CircleCI" && git config --global credential.helper store

      - run:
          name: Pip install requirements and pytest
          command: |
            sudo pip install -r requirements.txt
            sudo pip install coveralls pytest-cov
            mkdir /home/circleci/gigantum

      - run:
          name: Run mypy type checker
          command: |
            python -m mypy . --ignore-missing-imports --strict-optional
      - run:
          name: Run unit and coverage tests
          command: |
            redis-server &
            rqscheduler --interval=2 2> /dev/null &
            pytest --cov=lmcommon .
            coveralls

